<?php

use Krystal\Widget\GridWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="row">
	<!-- Context menu for items -->
	<ul id="contextMenu" class="dropdown-menu" role="menu">
		<li><a href="<?php echo $this->url('Menu:Admin:Item@indexAction'); ?>"><i class="glyphicon glyphicon-list"></i> <?php $this->show('Return to beginning'); ?></a></li>
		<li class="dropdown-header"><?php $this->show('Item'); ?></li>
        <?php if ($canHaveChildren): ?>
		<li><a href="#" data-button="add-child"><i class="glyphicon glyphicon-share"></i> <?php $this->show('Add child item'); ?></a></li>
        <?php endif; ?>
		<li><a href="#" data-button="item-edit"><i class="glyphicon glyphicon-edit"></i> <?php $this->show('Edit this item'); ?></a></li>
		<li><a href="#" data-button="remove" data-base-removal-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', null); ?>" data-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', $item->getId()); ?>" data-success-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', $item->getCategoryId()); ?>" data-id=""><i class="glyphicon glyphicon-flash"></i> <?php $this->show('Remove this item'); ?></a></li>
        <?php if ($canHaveChildren): ?>
		<li class="dropdown-header"><?php $this->show('Nesting'); ?></li>
		<li><a href="#" data-button="expand-all"><i class="glyphicon glyphicon-resize-full"></i> <?php $this->show('Expand all'); ?></a></li>
		<li><a href="#" data-button="collapse-all"><i class="glyphicon glyphicon-resize-small"></i> <?php $this->show('Collapse all'); ?></a></li>
        <?php endif; ?>
	</ul>
	<!-- /Context menu for items -->

	<div class="col-lg-5">
		<?php if (!empty($itemsBlock)): ?>
		<div class="dd" data-url="<?php echo $this->url('Menu:Admin:Item@saveAction'); ?>"><?php echo $itemsBlock; ?></div>	
		<?php else: ?>

		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No items'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
	
	<div class="col-lg-7">
		<?php if (!empty($categories)): ?>
		<form data-add-child-url="<?php echo $this->url('Menu:Admin:Item@addChildAction', '{category}', '{parent}'); ?>" data-home-url="<?php echo $this->url('Menu:Admin:Item@indexAction'); ?>" data-category-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', null); ?>" data-item-url="<?php echo $this->url('Menu:Admin:Item@viewAction', null); ?>">
            <?php echo Element::hidden('category_id', $item->getCategoryId()); ?>
            <?php echo Element::hidden('id', $item->getId()); ?>
            <?php echo Element::hidden('has_link', $item->getHasLink()); ?>
            <?php echo Element::hidden('max_depth', $maxDepth); ?>

			<div class="table-responsive">
				<form class="form-horizontal">
				  <fieldset>
					<legend class="text-muted"><i class="glyphicon glyphicon-list"></i> <?php $this->show($helper_title); ?></legend>

					<div class="form-group">
					  <label for="inputName" class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::text('name', $item->getName(), array('id' => 'inputName', 'class' => 'form-control', 'placeholder' => $this->translate('Item name'))); ?>
					  </div>
					</div>

					<div class="form-group">
					  <label for="chosenSelect" class="col-lg-2 control-label"><?php $this->show('Link'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::select('web_page_id', $links, $item->getWebPageId(), array('class' => 'chosen-select form-control', 'id' => 'chosenSelect')); ?>
					  </div>
					</div>

					<div class="form-group" id="custom-link-row">
					  <label for="inputLink" class="col-lg-2 control-label"><?php $this->show('Type a link'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::text('link', $item->getLink(), array('class' => 'form-control', 'id' => 'inputLink', 'placeholder' => $this->translate('http://'))); ?>
					  </div>
					</div>

					<?php if (!$item->getId() && $canHaveChildren): ?>
					<div class="form-group">
					  <label for="select" class="col-lg-2 control-label"><?php $this->show('Parent item'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::select('parent_id', $items, $item->getParentId(), array('class' => 'form-control', 'id' => 'select'), '— ' . $this->translate('None') . ' —'); ?>
					  </div>
					</div>
					<?php endif; ?>

					<div class="form-group">
					  <label for="hint" class="col-lg-2 control-label"><?php $this->show('Hint'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::textarea('hint', $item->getHint(), array('rows' => 3, 'class' => 'form-control', 'id' => 'hint', 'placeholder' => $this->translate('Hint to be displayed when mouse overs'))); ?>
					  </div>
					</div>

					<div class="form-group">
					  <label for="icon" class="col-lg-2 control-label"><?php $this->show('Icon'); ?></label>
					  <div class="col-lg-10">
                        <?php echo Element::textarea('icon', $item->getIcon(), array('class' => 'form-control', 'id' => 'icon', 'placeholder' => $this->translate('Optional font-icon'))); ?>
					  </div>
					</div>

					<div class="form-group">
					  <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					  <div class="col-lg-10">
						<div class="checkbox">
						  <label><?php echo Element::checkbox('published', $item->getPublished()); ?></label>
						</div>
					  </div>
					</div>

					<div class="form-group">
					  <label class="col-lg-2 control-label"><?php $this->show('Open in new window'); ?></label>
					  <div class="col-lg-10">
						<div class="checkbox">
						  <label><?php echo Element::checkbox('open_in_new_window', $item->getOpenInNewWindow()); ?></label>
						</div>
					  </div>
					</div>
				  </fieldset>
				</form>
			</div>
		</form>
		
		<br />
		
		<div class="pull-right">
			<?php if ($item->getId()): ?>
			<div class="btn-group">
			  <a class="btn btn-primary" data-button="save" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></a>
			  <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
			  <ul class="dropdown-menu">
				<li><a href="#" data-button="save-create" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></a></li>
				<li><a href="#" data-button="save-exit" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Exit'); ?></a></li>
			  </ul>
			</div>
			
			<button class="btn btn-primary" data-button="remove" data-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', $item->getId()); ?>" data-success-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', $item->getCategoryId()); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Remove'); ?></button>
			<button class="btn btn-default" data-button="cancel"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Cancel'); ?></button>
			<?php else: ?>

			<div class="btn-group pull-right">
			  <button type="submit" class="btn btn-primary" data-button="add" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
			  <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
			  
			  <ul class="dropdown-menu">
				<li><a href="#" data-button="create-new" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></a></li>
				<li><a href="#" data-button="create-exit" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Exit'); ?></a></li>
			  </ul>
			</div>
			<?php endif; ?>
		</div>

		<?php else: ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><small><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('To start using menu module, you need to create at least one category'); ?></small></h2>
		</div>
		<?php endif; ?>
	</div>
</div>

<div class="clearfix"></div>

<div class="table-responsive">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

    <?= $this->widget(new GridWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'rowAttributes' => array(
            'class' => function($category) use ($item){
                return $category->getId() == $item->getCategoryId() ? 'info' : null;
            }
        ),
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
                'value' => function($category){
                    return Element::link($category->getName(), $this->url('Menu:Admin:Item@categoryAction', $category->getId()));
                }
            ),

            array(
                'column' => 'max_depth',
                'label' => 'Maximal depth'
            ),

            array(
                'column' => 'class',
                'hidden' => !$extendedMode
            )
        ),

        'actions' => $extendedMode ? array(
            'edit' => function($category){
                return Icon::edit(
                    $this->url('Menu:Admin:Category@editAction', $category->getId()),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($category){
                return Icon::remove(
                    $this->url('Menu:Admin:Category@deleteAction', $category->getId()),
                    $this->translate('Remove the category with all its items'),
                    null,
                    $this->url('Menu:Admin:Item@indexAction')
                );
            }
        ) : null
    ))); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
	</div>
    <?php endif; ?>

    <?php if ($extendedMode): ?>
	<div class="pull-left">
        <a href="<?php echo $this->url('Menu:Admin:Category@addAction'); ?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-floppy-disk"></i> <?php $this->show('Add category'); ?></a>
	</div>
	<?php endif; ?>
</div>
