<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="row">
        <!-- Context menu for items -->
        <div id="contextMenu" class="dropdown-menu" role="menu">
            <a class="dropdown-item" href="<?php echo $this->url('Menu:Admin:Item@indexAction'); ?>"><i class="fas fa-bars"></i> <?php $this->show('Return to beginning'); ?></a>
            <div class="dropdown-header"><?php $this->show('Item'); ?></div>
            <?php if ($canHaveChildren): ?>
            <a class="dropdown-item" href="#" data-button="add-child"><i class="fas fa-share-square"></i> <?php $this->show('Add child item'); ?></a>
            <?php endif; ?>
            <a class="dropdown-item" href="#" data-button="item-edit"><i class="fas fa-pencil-alt"></i> <?php $this->show('Edit this item'); ?></a>
            <a class="dropdown-item" href="#" data-button="remove" data-base-removal-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', null); ?>" data-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', $item->getId()); ?>" data-success-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', $item->getCategoryId()); ?>" data-id=""><i class="fas fa-trash-alt"></i> <?php $this->show('Remove this item'); ?></a>
            <?php if ($canHaveChildren): ?>
            <div class="dropdown-header"><?php $this->show('Nesting'); ?></div>
            <a class="dropdown-item" href="#" data-button="expand-all"><i class="fas fa-expand-arrows-alt"></i> <?php $this->show('Expand all'); ?></a>
            <a class="dropdown-item" href="#" data-button="collapse-all"><i class="fas fa-compress-arrows-alt"></i> <?php $this->show('Collapse all'); ?></a>
            <?php endif; ?>
        </div>
        <!-- /Context menu for items -->

        <div class="col-lg-6">
            <?php if (!empty($itemsBlock)): ?>
            <div class="dd" data-url="<?php echo $this->url('Menu:Admin:Item@saveAction'); ?>"><?php echo $itemsBlock; ?></div>	
            <?php else: ?>

            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No items'); ?></h2>
            </div>
            <?php endif; ?>
        </div>

        <div class="col-lg-6">
            <?php if (!empty($categories)): ?>
            <form  autocomplete="off" data-add-child-url="<?php echo $this->url('Menu:Admin:Item@addChildAction', '{category}', '{parent}'); ?>" data-home-url="<?php echo $this->url('Menu:Admin:Item@indexAction'); ?>" data-category-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', null); ?>" data-item-url="<?php echo $this->url('Menu:Admin:Item@viewAction', null); ?>">
                <?php echo Element::hidden('category_id', $item->getCategoryId()); ?>
                <?php echo Element::hidden('id', $item->getId()); ?>
                <?php echo Element::hidden('has_link', $item->getHasLink()); ?>
                <?php echo Element::hidden('max_depth', $maxDepth); ?>

                <div class="form-horizontal">
                  <fieldset>
                    <legend class="text-muted"><i class="glyphicon glyphicon-list"></i> <?php $this->show($helper_title); ?></legend>

                    <div class="form-group">
                      <label for="inputName" class="col-lg-12"><?php $this->show('Name'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::text('name', $item->getName(), array('id' => 'inputName', 'class' => 'form-control', 'placeholder' => $this->translate('Item name'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="chosenSelect" class="col-lg-12"><?php $this->show('Link'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::select('web_page_id', $links, $item->getWebPageId(), array('class' => 'chosen-select form-control', 'id' => 'chosenSelect')); ?>
                      </div>
                    </div>

                    <div class="form-group" id="custom-link-row">
                      <label for="inputLink" class="col-lg-12"><?php $this->show('Type a link'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::text('link', $item->getLink(), array('class' => 'form-control', 'id' => 'inputLink', 'placeholder' => $this->translate('http://'))); ?>
                      </div>
                    </div>

                    <?php if (!$item->getId() && $canHaveChildren): ?>
                    <div class="form-group">
                      <label for="select" class="col-lg-12"><?php $this->show('Parent item'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::select('parent_id', $items, $item->getParentId(), array('class' => 'form-control', 'id' => 'select'), '— ' . $this->translate('None') . ' —'); ?>
                      </div>
                    </div>
                    <?php endif; ?>

                    <div class="form-group">
                      <label for="hint" class="col-lg-12"><?php $this->show('Hint'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::textarea('hint', $item->getHint(), array('rows' => 3, 'class' => 'form-control', 'id' => 'hint', 'placeholder' => $this->translate('Hint to be displayed when mouse overs'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="icon" class="col-lg-12"><?php $this->show('Icon'); ?></label>
                      <div class="col-lg-12">
                        <?php echo Element::textarea('icon', $item->getIcon(), array('class' => 'form-control', 'id' => 'icon', 'placeholder' => $this->translate('Optional font-icon'))); ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-12"><?php $this->show('Published'); ?></label>
                      <div class="col-lg-12">
                        <div class="checkbox">
                          <label><?php echo Element::checkbox('published', $item->getPublished()); ?></label>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-12"><?php $this->show('Open in new window'); ?></label>
                      <div class="col-lg-12">
                        <div class="checkbox">
                          <label><?php echo Element::checkbox('open_in_new_window', $item->getOpenInNewWindow()); ?></label>
                        </div>
                      </div>
                    </div>
                  </fieldset>
                </div>
            </form>
            
            <br />

            <div>
                <?php if ($item->getId()): ?>
                <div class="btn-group">
                  <a class="btn btn-primary btn-lg" data-button="save" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></a>

                  <div class="btn-group">
                      <a href="#" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="#" data-button="save-create" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></a>
                        <a class="dropdown-item" href="#" data-button="save-exit" data-url="<?php echo $this->url('Menu:Admin:Item@updateAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Exit'); ?></a>
                      </div>
                  </div>
                </div>
                
                <button class="btn btn-primary btn-lg" data-button="remove" data-url="<?php echo $this->url('Menu:Admin:Item@deleteAction', $item->getId()); ?>" data-success-url="<?php echo $this->url('Menu:Admin:Item@categoryAction', $item->getCategoryId()); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Remove'); ?></button>
                <a href="<?= $this->url('Menu:Admin:Item@categoryAction', $item->getCategoryId()); ?>" class="btn btn-danger btn-lg"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Cancel'); ?></a>
                
                <?php else: ?>

                <div class="btn-group">
                    <button type="submit" class="btn btn-primary" data-button="add" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>

                    <div class="btn-group">
                      <a href="#" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="#" data-button="create-new" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></a>
                        <a class="dropdown-item" href="#" data-button="create-exit" data-url="<?php echo $this->url('Menu:Admin:Item@addAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Exit'); ?></a>
                      </div>
                    </div>
                </div>

                <?php endif; ?>
            </div>

            <?php else: ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><small><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('To start using menu module, you need to create at least one category'); ?></small></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="card">
	<h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

    <?= $this->widget(new GridViewWidget($categories, [
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => [
            'class' => function($category) use ($item){
                return $category->getId() == $item->getCategoryId() ? 'table-info' : null;
            }
        ],
        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name',
                'attributes' => [
                    'class' => null
                ],
                'value' => function($category){
                    return Element::link($category->getName(), $this->url('Menu:Admin:Item@categoryAction', $category->getId()));
                }
            ],

            [
                'column' => 'max_depth',
                'label' => 'Maximal depth'
            ],

            [
                'column' => 'class',
                'hidden' => !$extendedMode
            ]
        ],

        'actions' => $extendedMode ? [
            'truncate' => function($category){
                return Icon::reset(
                    $this->url('Menu:Admin:Category@truncateAction', $category->getId()),
                    $this->translate('Truncate this category'),
                    $this->translate('This will remove all items inside this category, are you sure?'),
                    $this->url('Menu:Admin:Item@categoryAction', $category->getId())
                );
            },

            'edit' => function($category){
                return Icon::edit(
                    $this->url('Menu:Admin:Category@editAction', $category->getId()),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($category){
                return Icon::remove(
                    $this->url('Menu:Admin:Category@deleteAction', $category->getId()),
                    $this->translate('Remove the category with all its items'),
                    null,
                    $this->url('Menu:Admin:Item@indexAction')
                );
            }
        ] : null
    ])); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
	</div>
    <?php endif; ?>

    <?php if ($extendedMode): ?>
	<div class="pull-left">
        <a href="<?php echo $this->url('Menu:Admin:Category@addAction'); ?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-floppy-disk"></i> <?php $this->show('Add category'); ?></a>
	</div>
	<?php endif; ?>
</div>
