
<div class="menu-widget-btn-container">
	<input type="hidden" name="widget-load-url" value="<?php echo $this->url('Menu:Admin:Widget@loadWigdetAction', null); ?>" />
    <button data-button="add-item" data-url="<?php echo $this->url('Menu:Admin:Widget@loadEmptyAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-align-center"></i> <?php $this->show('Add an item'); ?></button>
</div>

<div class="well clearfix" data-container="menu-widget"></div>